FROM python:3.11.9-slim as debian
LABEL source = "https://github.com/Superxpdude/blue-on-blue"

# Update installed packages and install tools for backups
RUN apt-get update && \
	apt-get upgrade -y && \
	apt-get install sqlite3 zip -y && \
	apt-get autoremove -y && \
	apt-get clean

# Select the working directory
WORKDIR /app

# Copy necessary files to the container
COPY ./src src
COPY ./pyproject.toml ./
COPY --chmod=755 ./scripts/container.sh ./entrypoint.sh
COPY --chmod=755 ./scripts/backup.sh /usr/local/bin/backup

# Create a python virtual environment
ENV VIRTUAL_ENV=/opt/venv
RUN python -m venv $VIRTUAL_ENV
# Add the venv to the front of the path so that it gets used
# by default for future python calls
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# Install python dependencies
RUN pip install -U pip
RUN pip install .

VOLUME ["/app/data"]

CMD ["start"]
ENTRYPOINT ["/app/entrypoint.sh"]
