[build-system]
requires = ["setuptools>=70.0.0"]
build-backend = "setuptools.build_meta"

[project]
version = "0.1.0"
authors = [{ name = "Superxpdude" }]
name = "blueonblue"
description = "Discord Bot for TMTM"
requires-python = ">=3.11"

[project.urls]
Repository = "https://github.com/Superxpdude/blue-on-blue"

[tool.ruff.format]
indent-style = "tab"
