name: Deploy Containers

on:
  push:
    branches:
      - "main"
      - "dev"

jobs:
  build:
    name: Build container
    uses: ./.github/workflows/build_containers.yaml
    id: build-image
    with:
      tag: ${{ github.ref == 'refs/heads/main' && 'latest' || 'dev'}}

  deploy:
    name: Deploy image
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io/superxpdude

    steps:
      - name: Log in to the GitHub Container registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to the GitHub Container Repository
        id: push-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ jobs.build-image.outputs.image }}
          tags: ${{ jobs.build-image.outputs.tags }}
          registry: ${{ env.REGISTRY }}

      - name: Print image URL
        run: echo "Image pushed to ${{ steps.push-to-ghcr.outputs.registry-paths }}"
