name: Deploy Release Container

on:
  release:
    types: ["published"]

jobs:
  get-version:
    name: Get release version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - name: Get version
        id: get-version
        run: |
          version=$(echo ${{ github.ref_name }} | cut -c 2-)
          echo "version=$version" >> $GITHUB_OUTPUT


  build:
    name: Build container
    needs: get-version
    uses: ./.github/workflows/build_container.yaml
    with:
      version: ${{ needs.get-version.outputs.version }}

  deploy:
    name: Deploy image
    needs: [get-version, build]
    runs-on: ubuntu-latest
    permissions:
      attestations: write
      id-token: write
      packages: write
    env:
      IMAGE_NAME: blueonblue
      TAG: "latest"
      REGISTRY: ghcr.io/superxpdude

    steps:
      - name: Download container image
        uses: actions/download-artifact@v4
        with:
          name: blueonblue.tar
          path: /tmp

      - name: Import container image
        run: |
          buildah pull oci-archive:/tmp/blueonblue.tar

      - name: Apply container tags
        run: |
          buildah tag ${{ needs.build.outputs.image }} ${{ needs.build.outputs.image }}:${{ env.TAG }}
          buildah tag ${{ needs.build.outputs.image }} ${{ needs.build.outputs.image }}:${{ needs.get-version.outputs.version }}

      - name: Display buildah containers
        run: |
          buildah images -a

      - name: Log in to the GitHub Container registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to the GitHub Container Repository
        id: push-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ needs.build.outputs.image }}
          tags: ${{ env.TAG }} ${{ needs.get-version.outputs.version }} ${{ needs.build.outputs.tags }}
          registry: ${{ env.REGISTRY }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push-to-ghcr.outputs.digest }}
          push-to-registry: true

      - name: Print image URL
        run: echo "Image pushed to ${{ steps.push-to-ghcr.outputs.registry-paths }}"
