name: Type Checking

on:
  push:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10","3.11"]

    name: check ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up CPython ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-tests.txt ]; then pip install -r requirements-tests.txt; fi
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Run Pyright
        uses: jakebailey/pyright-action@v1
        with:
          warnings: false
